### ISSUE TITLE
Fail with SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Akiyamka** [js-kyle/npm-viewscripts#12]
```sh
   ➜  npx npm-viewscripts
Need to install the following packages:
  npm-viewscripts
Ok to proceed? (y) y

No potentially unsafe scripts found.
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /home/username/.npm/_npx/b4f17dfd428193b3/node_modules/npm-viewscripts/index.js:12:22
    at directoryTree (/home/cherrytea/.npm/_npx/b4f17dfd428193b3/node_modules/directory-tree/lib/directory-tree.js:108:7)
    at /home/username/.npm/_npx/b4f17dfd428193b3/node_modules/directory-tree/lib/directory-tree.js:121:21
    at Array.map (<anonymous>)
    at directoryTree (/home/cherrytea/.npm/_npx/b4f17dfd428193b3/node_modules/directory-tree/lib/directory-tree.js:121:8)
    at /home/username/.npm/_npx/b4f17dfd428193b3/node_modules/directory-tree/lib/directory-tree.js:121:21
    at Array.map (<anonymous>)
    at directoryTree (/home/cherrytea/.npm/_npx/b4f17dfd428193b3/node_modules/directory-tree/lib/directory-tree.js:121:8)
    at /home/username/.npm/_npx/b4f17dfd428193b3/node_modules/directory-tree/lib/directory-tree.js:121:21
   
➜  node -v
v16.4.1

➜ npm -v
7.19.1
   
  ```

**Comment by js-kyle** [comment]
Thanks for the bug report - I will take a look

**Comment by diyfr** [comment]
[PR15](https://github.com/js-kyle/npm-viewscripts/pull/15)
